version: 0.2

phases:
  install:
    runtimeVersions:
      java: corretto11
      docker: 19
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

artifacts:
  files:
    - target/*.jar
  discardPaths: yes

cache:
  paths:
    - '/root/.m2/**/*'