openapi: 3.0.3
info:
  version: 1.0.0
  title: realmeet
  contact:
    name: A-Team
    email: a-team@goarmy.com
  description: The number of extension points.
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Rooms
paths:
  /rooms/id:
    get:
      tags:
        - Rooms
      description: The number of extension points.
      summary: Return rooms
      operationId: handler
      parameters:
        - name: roomId
          in: query
          description: ID of the room
          schema:
            type: integer
            format: int64
          examples:
            roomId:
              value: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
              example:
                id: 1
                code: 97b2393c-255a-4237-8eaf-56b8ab2597f7
                name: '#Room 1'
                seats: 4
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Room:
      type: object
      properties:
        roomId:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
        seats:
          type: integer
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
